# Generated by Django 3.0.7 on 2020-11-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=250, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Anti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250, verbose_name='Nome')),
                ('eficacia', models.TextField(max_length=100, verbose_name='Eficacia')),
                ('pros', models.TextField(max_length=500, verbose_name='Prós')),
                ('contra', models.TextField(max_length=500, verbose_name='Contra')),
                ('regime', models.TextField(default='Permanente', max_length=100, verbose_name='Regime')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('descurta', models.TextField(max_length=500, verbose_name='Descrição curta')),
                ('deslonga', models.TextField(max_length=2000, verbose_name='Descrição longa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Categoria')),
            ],
        ),
    ]
