# Generated by Django 3.0.7 on 2020-11-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra', models.BooleanField(max_length=250, verbose_name='Regras')),
            ],
            options={
                'verbose_name': 'Regra',
                'verbose_name_plural': 'Regras',
                'ordering': ['regra'],
            },
        ),
        migrations.AlterModelOptions(
            name='anti',
            options={'ordering': ['name'], 'verbose_name': 'Anticoncepcional', 'verbose_name_plural': 'anticoncepcionais'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='anti',
            name='eficacia',
            field=models.CharField(max_length=100, verbose_name='Eficacia'),
        ),
        migrations.AlterField(
            model_name='anti',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='anti',
            name='regime',
            field=models.CharField(default='Permanente', max_length=100, verbose_name='Regime'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=250, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=250, verbose_name='Resposta')),
                ('obs', models.TextField(max_length=2000, verbose_name='Observação')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Regra', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['resposta'],
            },
        ),
        migrations.AddField(
            model_name='regra',
            name='anti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Anti', verbose_name='Anticomcepcional'),
        ),
    ]
