# Generated by Django 3.0.7 on 2020-11-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regra',
            options={'ordering': ['id'], 'verbose_name': 'Regra', 'verbose_name_plural': 'Regras'},
        ),
        migrations.AddField(
            model_name='regra',
            name='pergunta',
            field=models.CharField(default='', max_length=250, verbose_name='Você está amamentando um bebê com menos de seis meses de idade?'),
        ),
        migrations.AlterField(
            model_name='anti',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='anti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Anti', verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='regra',
            field=models.BooleanField(default=False, verbose_name='Resposta'),
        ),
    ]
