# Generated by Django 3.0.7 on 2020-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201102_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.BooleanField(default=False, verbose_name='Você está amamentando um bebê com menos de seis meses de idade?')),
                ('p2', models.BooleanField(default=False, verbose_name='Você teve nenê nas últimas três semanas e não está amamentando?')),
                ('p3', models.BooleanField(default=False, verbose_name='Você fuma cigarros?')),
                ('p4', models.BooleanField(default=False, verbose_name='Você tem cirrose no fígado, alguma infecção ou tumor hepático?')),
                ('p5', models.BooleanField(default=False, verbose_name='Você tem pressão arterial alta?')),
                ('p6', models.BooleanField(default=False, verbose_name='Você já teve diabetes por mais de 20 anos ou algum dano em suas artérias, visão, rins ou sistema nervoso causado por diabetes?')),
                ('p7', models.BooleanField(default=False, verbose_name='Você tem doença da vesícula biliar no momento ou toma medicação para esta doença?')),
                ('p8', models.BooleanField(default=False, verbose_name='Você já teve um derrame, um coágulo sangüíneo em suas pernas ou nos pulmões, infarto ou outros problemas cardíacos graves?')),
                ('p9', models.BooleanField(default=False, verbose_name='Você tem ou já teve câncer de mama?')),
                ('p10', models.BooleanField(default=False, verbose_name='Você planeja submeter-se a uma cirurgia que a impedirá de andar por uma semana ou mais?')),
                ('p12', models.BooleanField(default=False, verbose_name='Você tem atualmente algum problema sério com coágulo sangüíneo nas suas pernas ou nos pulmões?')),
                ('p13', models.BooleanField(default=False, verbose_name='Você está tomando medicação para ataques convulsivos? Está tomando rifampicina para tuberculose ou outra doença?')),
                ('p14', models.BooleanField(default=False, verbose_name='Você tem ou já teve câncer de mama?')),
                ('p21', models.BooleanField(default=False, verbose_name='Você tem sangramento vaginal que é algo incomum para você?')),
                ('p22', models.BooleanField(default=False, verbose_name='Você apresenta diversos fatores que possam aumentar sua probabilidade de doença cardíaca (doença da artéria coronária) ou derrame (acidente vascular cerebral), tais como idade avançada, fumo, pressão arterial alta ou diabetes?')),
                ('p31', models.BooleanField(default=False, verbose_name='Você às vezes vê uma área brilhante de visão apagada no olho antes de uma dor de cabeça intensa (aura de enxaqueca)? Você tem latejamento, forte dor de cabeça, freqüentemente em apenas um lado da cabeça, que pode durar de algumas horas a vários dias e pode causar náusea ou vômitos (dores de cabeça com enxaqueca)? Tais dores de cabeça freqüentemente pioram com a luz, barulho ou ao se mover.')),
                ('p32', models.BooleanField(default=False, verbose_name='Você fuma 15 cigarros ou mais por dia?')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='categoria/', verbose_name='Categória'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='pergunta',
            field=models.CharField(default='', max_length=250, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.BooleanField(max_length=250, verbose_name='Resposta'),
        ),
    ]
