# Generated by Django 3.0.7 on 2020-11-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201126_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='metodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Anti'),
        ),
    ]
