# Generated by Django 3.0.7 on 2020-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pergunta_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='similaridade',
            field=models.FloatField(default=0, verbose_name='RESULTADO'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p1',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você teve bebê nas últimas três semanas?'),
        ),
    ]
