# Generated by Django 3.0.7 on 2021-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201126_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='p11',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='p12',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='p13',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='p14',
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p1',
            field=models.DateField(choices=[('A MAIS DE UM MÊS', 'A MAIS DE UM MÊS'), ('A MAIS DE QUATRO MESES', 'A MAIS DE QUATRO MESES'), ('A MAIS DE NOVE MESES', 'A MAIS DE NOVE MESES'), ('A MAIS DE UM ANO', 'A MAIS DE UM ANO')], default='', max_length=200, verbose_name='Qual foi a data do ultimo parto?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p10',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Voce tem sangramento vaginal fora da menstruação?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p3',
            field=models.CharField(choices=[('SIM, FUMO', 'SIM, FUMO'), ('ALGUMAS VEZES', 'ALGUMAS VEZES'), ('NÃO, NÃO FUMO', 'NÃO, NÃO FUMO')], default='', max_length=200, verbose_name='Você fuma?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p4',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('NÃO SEI', 'NÃO SEI'), ('TALVEZ', 'TALVEZ')], default='', max_length=200, verbose_name='Voce teve alguma infermidade no figado? '),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p5',
            field=models.CharField(choices=[('SIM (TENHO PRESSÃO ALTA)', 'SIM (TENHO PRESSÃO ALTA)'), ('SIM (TENHO PRESSÃO BAIXA)', 'SIM (TENHO PRESSÃO BAIXA)'), ('NÃO (NÃO TENHO)', 'NÃO (NÃO TENHO)'), ('NÃO SEI', 'NÃO SEI')], default='', max_length=200, verbose_name='Voce sofre de hipertensão alterial?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p6',
            field=models.CharField(choices=[('SIM TENHO', 'SIM TENHO'), ('NÃO TENHO', 'NÃO TENHO'), ('JÁ TIVE', 'JÁ TIVE')], default='', max_length=200, verbose_name='Você já teve diabetes ?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p7',
            field=models.CharField(choices=[('sim', 'SIM'), ('não', 'NÃO')], default='', max_length=200, verbose_name='Você toma medicação para alguma doença cronica?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p8',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você já teve um derrame? '),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p9',
            field=models.CharField(choices=[('TENHO', 'TENHO'), ('SIM (JÁ TIVE)', 'SIM (JÁ TIVE)'), ('NÃO (NUNCA TIVE)', 'NÃO (NUNCA TIVE)')], default='', max_length=200, verbose_name='Você tem  câncer de mama?'),
        ),
    ]
