# Generated by Django 3.0.7 on 2021-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210223_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='p1',
            field=models.CharField(choices=[('A MAIS DE UM MÊS', 'A MAIS DE UM MÊS'), ('A MAIS DE QUATRO MESES', 'A MAIS DE QUATRO MESES'), ('A MAIS DE NOVE MESES', 'A MAIS DE NOVE MESES'), ('A MAIS DE UM ANO', 'A MAIS DE UM ANO')], default='', max_length=200, verbose_name='Qual foi a data do ultimo parto?'),
        ),
    ]
