# Generated by Django 2.2.14 on 2021-05-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210223_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='p11',
            field=models.CharField(choices=[('SIM (JÁ TIVE)', 'SIM (JÁ TIVE)'), ('NÃO (NUNCA TIVE)', 'NÃO (NUNCA TIVE)')], default='', max_length=200, verbose_name='Você ja teve um coágulo sangüíneo em seus pulmões?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p12',
            field=models.CharField(choices=[('SIM (JÁ TIVE)', 'SIM (JÁ TIVE)'), ('NÃO (NUNCA TIVE)', 'NÃO (NUNCA TIVE)')], default='', max_length=200, verbose_name='Você ja teve um coágulo sangüíneo em seuas pernas'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p13',
            field=models.CharField(choices=[('TENHO', 'TENHO'), ('SIM (JÁ TIVE)', 'SIM (JÁ TIVE)'), ('NÃO (NUNCA TIVE)', 'NÃO (NUNCA TIVE)')], default='', max_length=200, verbose_name='Você tem  câncer de mama?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p14',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem sangramento vaginal?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p1',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você teve bebê nas últimas três semanas?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p10',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você já teve um derrame? '),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p3',
            field=models.CharField(choices=[('SIM FUMO (1 há 5)', 'SIM FUMO (1 há 5)'), ('SIM FUMO (5 há 10)', 'SIM FUMO (5 há 10)'), ('SIM FUMO (10 há 20)', 'SIM FUMO (10 há 20)'), ('NÃO, NÃO FUMO', 'NÃO, NÃO FUMO')], default='', max_length=200, verbose_name='Você fuma cigarros?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p4',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('NÃO SEI', 'NÃO SEI'), ('TALVEZ', 'TALVEZ')], default='', max_length=200, verbose_name='Você tem cirrose no fígado? '),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p5',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO'), ('NÃO SEI', 'NÃO SEI'), ('TALVEZ', 'TALVEZ')], default='', max_length=200, verbose_name='Voce tem algum tumor hepático?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p6',
            field=models.CharField(choices=[('SIM (TENHO PRESSÃO ALTA)', 'SIM (TENHO PRESSÃO ALTA)'), ('SIM (TENHO PRESSÃO BAIXA)', 'SIM (TENHO PRESSÃO BAIXA)'), ('NÃO (NÃO TENHO)', 'NÃO (NÃO TENHO)'), ('NÃO SEI', 'NÃO SEI')], default='', max_length=200, verbose_name='Você tem pressão arterial ?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p7',
            field=models.CharField(choices=[('SIM TENHO', 'SIM TENHO'), ('NÃO TENHO', 'NÃO TENHO'), ('JÁ TIVE', 'JÁ TIVE')], default='', max_length=200, verbose_name='Você já teve diabetes ?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p8',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem doença da vesícula biliar?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p9',
            field=models.CharField(choices=[('sim', 'SIM'), ('não', 'NÃO')], default='', max_length=200, verbose_name='Você toma medicação para alguma doença cronica?'),
        ),
    ]
