# Generated by Django 2.2.14 on 2021-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210518_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anti',
            name='eficacia',
            field=models.IntegerField(default=1, verbose_name='Eficacia'),
        ),
    ]
