# Generated by Django 2.2.14 on 2021-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210603_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='p6',
            field=models.CharField(choices=[('SIM (TENHO PRESSÃO ALTA)', 'SIM (TENHO PRESSÃO ALTA)'), ('SIM (TENHO PRESSÃO BAIXA)', 'SIM (TENHO PRESSÃO BAIXA)'), ('NÃO (NÃO TENHO)', 'NÃO (NÃO TENHO)'), ('NÃO SEI', 'NÃO SEI')], default='', max_length=200, verbose_name='Você tem tensão arterial ?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p7',
            field=models.CharField(choices=[('SIM TENHO', 'SIM TENHO'), ('NÃO TENHO', 'NÃO TENHO'), ('JÁ TIVE', 'JÁ TIVE')], default='', max_length=200, verbose_name='Você tem diabetes ?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p9',
            field=models.CharField(choices=[('sim', 'SIM'), ('não', 'NÃO')], default='', max_length=200, verbose_name='Você toma medicação para alguma doença crônica?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='similaridade',
            field=models.IntegerField(default=0, verbose_name='RESULTADO'),
        ),
    ]
