# Generated by Django 2.2.14 on 2021-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210603_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='p15',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem uma vida sexual ativa?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p16',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você  faz sexo casual?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p17',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem mais de um parceiro sexual?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p18',
            field=models.CharField(choices=[('DENTRO DE 6 MESES', 'DENTRO DE 6 MESES'), ('DENTRO DE 1 ANO', 'DENTRO DE 1 ANO'), ('DENTRO DE 2 ANOS', 'DENTRO DE 2 ANOS'), ('DENTRO DE 3 À 5 ANOS', 'DENTRO DE 3 À 5 ANOS')], default='', max_length=200, verbose_name='Você pretende engravidar dentro de quanto tempo?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p19',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você é alérgico(a) a perservativo?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p20',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Práticas alguma atividade física?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p21',
            field=models.CharField(choices=[('6 MESES', '6 MESES'), ('1 ANO', '1 ANO'), ('2 ANOS', '2 ANOS'), ('3 ANOS OU MAIS', '3 ANOS OU MAIS')], default='', max_length=200, verbose_name='Qual foi a data do último parto?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p22',
            field=models.CharField(choices=[('DE FORMA MODERADA', 'DE FORMA MODERADA'), ('COM BASTANTE FREQUÊNCIA', 'COM BASTANTE FREQUÊNCIA'), ('NÃO CONSUMO', 'NÃO CONSUMO')], default='', max_length=200, verbose_name='Com que frequência  consomes bebidas alcoólica?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p23',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você teve algum enfermidade no fígado?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p24',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você já teve uma AVC?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p25',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem antecedentes de câncer na família?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='p26',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem mais de um parceiro sexual?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='p14',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem sangramento vaginal fora da menstruação?'),
        ),
    ]
