# Generated by Django 2.2.14 on 2021-06-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210610_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='p7',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='', max_length=200, verbose_name='Você tem diabetes ?'),
        ),
    ]
